### ISSUE TITLE
SchemaSpyGui Integration

### ISSUE THREAD

**Issue by ancgate** [adriens/schemaspy#1]
Is it possible to compile it and use it in SchemaSpyGUI? Thanks

**Comment by adriens** [comment]
I guess yes, it is. All you should do is to add this lib through jitpack so you can compile on it, can you give it a try ?

**Comment by adriens** [comment]
https://jitpack.io/

Just follow the steps and you will be done within less than 5 minutes :smiley:

**Comment by adriens** [comment]
I have just created a release so you will be able to reference ic

**Comment by ancgate** [comment]
Ok, Many Thanks. I will give it a  try.

**Comment by adriens** [comment]
Ok, i close the issue. Feel free to create a new one in case of need.
